// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xS5LG_mPj3q8FvRmSkbFurT74Rxrk0c',
    appId: '1:564829110484:web:7e4832515e4f73aef47b41',
    messagingSenderId: '564829110484',
    projectId: 'hairhub-303d4',
    authDomain: 'hairhub-303d4.firebaseapp.com',
    storageBucket: 'hairhub-303d4.appspot.com',
    measurementId: 'G-H1G8WHWWLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb2BHtXInqLlCoHuTWMPeZ-9oR8EAREyE',
    appId: '1:564829110484:android:2243edb9e74bcc06f47b41',
    messagingSenderId: '564829110484',
    projectId: 'hairhub-303d4',
    storageBucket: 'hairhub-303d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC03R5EZqtjxmyjBwJgHO2S-Id-b0KOMtw',
    appId: '1:564829110484:ios:108b725360fbfc59f47b41',
    messagingSenderId: '564829110484',
    projectId: 'hairhub-303d4',
    storageBucket: 'hairhub-303d4.appspot.com',
    iosBundleId: 'com.example.hairHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC03R5EZqtjxmyjBwJgHO2S-Id-b0KOMtw',
    appId: '1:564829110484:ios:108b725360fbfc59f47b41',
    messagingSenderId: '564829110484',
    projectId: 'hairhub-303d4',
    storageBucket: 'hairhub-303d4.appspot.com',
    iosBundleId: 'com.example.hairHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_xS5LG_mPj3q8FvRmSkbFurT74Rxrk0c',
    appId: '1:564829110484:web:df13fc12f2069821f47b41',
    messagingSenderId: '564829110484',
    projectId: 'hairhub-303d4',
    authDomain: 'hairhub-303d4.firebaseapp.com',
    storageBucket: 'hairhub-303d4.appspot.com',
    measurementId: 'G-GVEZ503S2V',
  );
}
